# Generated by Django 3.0.8 on 2020-08-03 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200803_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 13, 3, 42, 660841)),
        ),
    ]
